codecov:
  branch: master

coverage:
  precision: 2
  round: up

  ignore:
      - "common/src/com/google/common/graph/ConfigurableMutableGraph.java"
      - "common/src/com/google/common/graph/ConfigurableMutableValueGraph.java"
      - "common/src/com/google/common/graph/ElementOrder.java"
